@startuml
class 借阅记录{
    借阅日期
    借阅人ID
    图书编号
    数量
    归还情况
}
class 学生{
    学号
    姓名
    所属院系
}
class 老师{
    工号
    姓名
}

class 读者{
    读者ID
    读者类型
}
class 馆员{
    馆员ID
    馆员姓名
}
class 罚款{
    罚款人ID
    金额
    校园卡卡号
}
class 图书管理系统
class 预订记录{
    预约人ID
    预约日期
    预约书号
}
class 书目{
    书号
    书名
    作者
    出版社
    出版日期
    版本号
    ISBN
    总书本数
    借书数量
    预订数量
}
class 图书{
    图书编号
    图书状态
}
读者 <|-down-老师
读者 <|-right- 学生
借阅记录 "0..5" -down-"1" 读者:借阅
图书管理系统 "1"-right-"0..*"读者
读者 "0..1" -left- "0..3" 预订记录:预订
借阅记录 "0..n" -left- "1" 馆员:管理;
馆员 "1..*" -left-  "0..*"图书:管理
罚款 "1"-- "0..*"读者:+缴费
图书管理系统 -down- 罚款:查询
图书管理系统 "1"-left-"1" 书目:拥有
预订记录 "0..n" -left-  "0..1"书目:预订
图书 "n" -up-  "1" 书目


















@enduml