@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor ":Borrower" as User
note left of User #aqua
	借阅者查找
	图书时序图
end note
participant "SearchBookWindow" as A
participant ":Book" as B
User -> A: 1.查找图书信息
activate User
activate A
activate B
A -> B: 1.1 根据图书编号查找图书
B --> A: 1.1.1 返回图书信息
deactivate User
deactivate B
A -->User:1.2 显示图书信息
activate User
deactivate User
deactivate A
@enduml