@startuml

class 图书{
    图书编号:201103001
    图书状态:可借
}
class 书目{
    书号:9787040126614
    书名:信息系统分析与设计
    作者:赵卫东
    出版社:清华大学出版社
    出版日期:20151001
    版本号:第四版
    ISBN:978-302-32982-4
    总书本数:20
    借书数量:5
    预订数量:2
}
@enduml